Ignore rubocop-rspec warning about class names in doubles
Using the class name Response instead of a string throws
NameError: uninitialized constant Response.